blank_issues_enabled: false

contact_links:
  - name: 📚 Manual de Desenvolvimento
    url: https://github.com/quadritech-tecnologia/.github
    about: Consulte os padrões da organização antes de abrir uma nova atividade.
